### ISSUE TITLE
Throw error when selector matches more than one element and one is expected

### ISSUE THREAD

**Issue by krzysztof-jelski** [Pragmatists/ng-test-runner#1]
I verified that operations that use `find` in fact work on the first found element. Instead there should be an error raised that the selector matches more than one element.

It's also not in-line with the docs, as those claim the error will be raised.

Find uses `debugElement.query`, so in fact it's somehow related to how this function behaves.

**Comment by HubertLegec** [comment]
Will be fixed when #15 is merged.

**Comment by HubertLegec** [comment]
Fixed in v1.1.8
