### ISSUE TITLE
navigateToUrl doesn't work with on submodule when I use RouterModule.forChild(routes)

### ISSUE THREAD

**Issue by quentinbt** [Pragmatists/ng-test-runner#3]
Hi,
I can't test my router when I use RouterModule.forChild(routes) instead of RouterModule.forRoot(routes).
I get the error:

StaticInjectorError(Platform: core)[RouterLinkWithHref -> Router]:
NullInjectorError: No provider for Router!

Thank you for your job

Have a good day

**Comment by marmatys** [comment]
Hi,

How do you configure your module in tests? 

Here is my example:
```javascript
app = test(MyModule, RouterTestingModule.withRoutes([]));
```

When I remove `RouterTestingModule` I get same error as you.

**Comment by quentinbt** [comment]
Awesome, it works fine! One last question, I do not understand  how can I mock a  service
Thanks!

**Comment by marmatys** [comment]
In your test create `TestModule`. In that module set your mock as `provider` instead of your service.

Example:
```typescript
@NgModule({
    providers: [{
        provide: MyService,
        useClass: MyMockService
    }]
})
class TestModule {
}
```


Then during creation of testing module add `TestModule` **after** your production module.

Example:
```typescript
app = test(ProductionModule, TestModule, RouterTestingModule.withRoutes([]));
```
